In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import matplotlib.pyplot as plt
import scienceplots

import time
import math
import os
import random
from functools import partial
from decimal import Decimal
import numpy as np
import scipy.io as sio
import pysindy as ps
from tqdm import trange

from pymoo_ga import *
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.algorithms.moo.dnsga2 import DNSGA2
from pymoo.termination.default import DefaultMultiObjectiveTermination
from pymoo.optimize import minimize
from pymoo.core.problem import StarmapParallelization
from multiprocessing.pool import ThreadPool

from utils import *
from skimage.restoration import estimate_sigma
import bm3d
# from okridge.solvel0 import *
from solvel0 import solvel0, MIOSR
from best_subset import backward_refinement, brute_force_all_subsets
from UBIC import *
from kneed import KneeLocator
from bayesian_model_evidence import log_evidence

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, WhiteKernel
from sklearn.preprocessing import StandardScaler
from sklearn import covariance
from sklearn.metrics import mean_absolute_percentage_error

mrmr is not installed in the env you are using. This may cause an error in future if you try to use the (missing) lib.
L0BnB is not installed.


In [2]:
n_poly = 6
n_derivatives = 6
n_modules = 8

In [3]:
data_path = "../PDE-Discovery-EC/Datasets/"
data = sio.loadmat(os.path.join(data_path, "burgers.mat"))
u_clean = (data['usol']).real; u = u_clean.copy()
x = (data['x'][0]).real
t = (data['t'][:,0]).real
dt = t[1]-t[0]; dx = x[2]-x[1]

### Add noise

In [4]:
np.random.seed(0)
noise_type = "gaussian"
noise_lv = float(50)
print("Noise level:", noise_lv)
noise = 0.01*np.abs(noise_lv)*(u.std())*np.random.randn(u.shape[0],u.shape[1])
u = u + noise

Noise level: 50.0


### Denoise

In [5]:
# bm3d_file = f"./Denoised_data/burgers_{noise_type}{int(noise_lv)}_bm3d.npy"
# load_denoised_data = True
# if load_denoised_data:
#     print("Loading denoised data...")
#     u = np.load(bm3d_file)
# else:
#     kernel = RBF(length_scale=1, length_scale_bounds=(1e-2, 1e3)) + \
#                     WhiteKernel(noise_level=1, noise_level_bounds=(1e-10, 1e10))
    
#     xx = colvec(x)
#     u_mean = np.copy(u)
#     u_std = np.ones(u.shape)
#     for i in trange(len(t)):    
#         gpr = GaussianProcessRegressor(kernel=kernel, alpha=0.0, 
#                                        n_restarts_optimizer=10 # 20
#                                       )
    
#         gpr.fit(xx, u_mean[:, i])
#         um, ustd = gpr.predict(xx, return_std=True)
#         u_mean[:, i] = um
#         u_std[:, i] = ustd
    
#     est_sigma = u_std.mean() # max also works well
#     # est_sigma = (est_sigma+estimate_sigma(u))/2
#     u = bm3d.bm3d(u, sigma_psd=est_sigma, 
#                   stage_arg=bm3d.BM3DStages.ALL_STAGES, 
#                   blockmatches=(False, False))
    
#     ### to save ###
#     # np.save(bm3d_file, u)

np.random.seed(0)
fake_noise = np.random.normal(loc=0.0, scale=estimate_sigma(u), size=u.shape)
sigmas = estimate_sigma(u+fake_noise)*np.arange(0.1, 2., 0.1)
est_sigma = sigmas[np.argmin([((u-bm3d.bm3d(u+fake_noise, sigma_psd=sigma, stage_arg=bm3d.BM3DStages.ALL_STAGES, blockmatches=(False, False)))**2).mean() \
                              for sigma in sigmas])]
u = bm3d.bm3d(u, sigma_psd=est_sigma, 
                  stage_arg=bm3d.BM3DStages.ALL_STAGES, 
                  blockmatches=(False, False))

In [6]:
xt = np.array([x.reshape(-1, 1), t.reshape(1, -1)], dtype=object)
X, T = np.meshgrid(x, t)
XT = np.asarray([X, T]).T

In [7]:
function_library = ps.PolynomialLibrary(degree=n_poly, include_bias=False)

weak_lib = ps.WeakPDELibrary(
    function_library=function_library,
    derivative_order=n_derivatives,
    spatiotemporal_grid=XT,
    include_bias=True,
    diff_kwargs={"is_uniform":True},
    K=10000
)

X_pre = np.array(weak_lib.fit_transform(np.expand_dims(u, -1)))
y_pre = weak_lib.convert_u_dot_integral(np.expand_dims(u, -1))
feature_names = np.array(weak_lib.get_feature_names())

# R_path = "./Cache/"
# np.save(os.path.join(R_path, f"X_pre_burgers_noise{int(noise_lv)}.npy"), X_pre)
# np.save(os.path.join(R_path, f"y_pre_burgers_noise{int(noise_lv)}.npy"), y_pre)
# np.save(os.path.join(R_path, f"feature_names_burgers.npy"), feature_names)

In [8]:
base_poly = np.array([[p, 0] for p in range(1, n_poly+1)])
base_derivative = np.array([[0, d] for d in range(1, n_derivatives+1)])
modules = [(0, 0)] if weak_lib.include_bias else []
modules += [(p, 0) for p in range(1, n_poly+1)] + \
            [(0, d) for d in range(1, n_derivatives+1)] + \
            [tuple(p+d) for d in base_derivative for p in base_poly]
assert len(modules) == len(weak_lib.get_feature_names())
base_features = dict(zip(modules, X_pre.T))
u_t = y_pre.copy()

### Straightforward best-subset selection

In [9]:
# over 30 minutes for n_poly = 6 and n_derivatives = 6
# miosr_subsets = solvel0(X_pre, y_pre, miosr=True)

### Genetic algorithm with NSGA-II

In [10]:
pop_size = 500
order_complexity = False
pool = ThreadPool(4)
problem = PdeDiscoveryProblem(n_poly, n_derivatives, n_modules, 
                              base_features, u_t, order_complexity=order_complexity, 
                              elementwise_runner=StarmapParallelization(pool.starmap))

In [11]:
def add_prefix(file_path, prefix):
    dir_name, file_name = os.path.split(file_path)
    return os.path.join(dir_name, prefix + file_name)
    
load_pareto_front = False
n_max_gen = 200
n_max_evals = 100000
pf_file_path = f"./Cache/pf_SMSEMOA_burgers_noise{int(noise_lv)}.npy"

if not load_pareto_front:
    termination = DefaultMultiObjectiveTermination(
        xtol=1e-8,
        cvtol=1e-6,
        ftol=1e-8,
        period=50,
        n_max_gen=n_max_gen,
        n_max_evals=n_max_evals
    )
    
    from pymoo.algorithms.moo.sms import SMSEMOA
    from pymoo.algorithms.moo.age import AGEMOEA
    
    ### Optimization algorithms ###
    # algorithm = NSGA2(pop_size=pop_size,
    #                     sampling=PopulationSampling(),
    #                     crossover=GenomeCrossover(),
    #                     mutation=GenomeMutation(),
    #                     eliminate_duplicates=DuplicateElimination(),
    #                     )
    
    # algorithm = DNSGA2(pop_size=pop_size,
    #                 sampling=PopulationSampling(),
    #                 crossover=GenomeCrossover(),
    #                 mutation=GenomeMutation(),
    #                 eliminate_duplicates=DuplicateElimination(),
    #                 )
    
    algorithm = SMSEMOA(pop_size=pop_size,
                    sampling=PopulationSampling(),
                    crossover=GenomeCrossover(),
                    mutation=GenomeMutation(),
                    eliminate_duplicates=DuplicateElimination(),
                    )

    opt_time = time.time()
    res = minimize(problem, 
                   algorithm, 
                   termination=termination, 
                   verbose=True)
    opt_time = (time.time() - opt_time)/60
    print("Execution time:", opt_time)
    
    pareto_optimal_models = res.X
    # np.save(pf_file_path, pareto_optimal_models)

else:
    pareto_optimal_models = np.load(pf_file_path, allow_pickle=True)
    pass

np.random.seed(0)

n_gen  |  n_eval  | n_nds  |      eps      |   indicator  
     1 |      500 |      5 |             - |             -
     2 |     1000 |      6 |  0.0875620682 |             f
     3 |     1500 |      6 |  0.0325968859 |             f
     4 |     2000 |      7 |  0.0605442685 |             f
     5 |     2500 |      6 |  0.0330152751 |             f
     6 |     3000 |      6 |  0.0043363404 |         ideal
     7 |     3500 |      7 |  0.0159026193 |         ideal
     8 |     4000 |      8 |  0.0233800034 |             f
     9 |     4500 |      8 |  0.0034601105 |             f
    10 |     5000 |      7 |  0.0017469191 |             f
    11 |     5500 |      7 |  0.1666666667 |         nadir
    12 |     6000 |      8 |  0.0039322946 |         ideal
    13 |     6500 |      8 |  0.0031850232 |         ideal
    14 |     7000 |      9 |  0.0146075365 |             f
    15 |     7500 |      9 |  0.0000981385 |             f
    16 |     8000 |      9 |  0.0001685704 |            

In [12]:
### OPTIONAL: REFINE PARETO FRONT ###
from operator import itemgetter

effective_candidates = extract_unique_candidates(pareto_optimal_models)
new_pareto_optimal_models = []
for bs in backward_refinement([sorted([effective_candidates.index(_) for _ in list(pm[0])]) for pm in pareto_optimal_models], 
                              (problem.numericalize_genome(effective_candidates), y_pre)).get_best_subsets():
    bs = itemgetter(*bs)(effective_candidates)
    if type(bs[0]) is not tuple:
        bs = (bs,)
    new_pareto_optimal_models.append([frozenset(bs)])
pareto_optimal_models = np.array(new_pareto_optimal_models)
del new_pareto_optimal_models
pareto_optimal_models

array([[frozenset({(0, 1)})],
       [frozenset({(1, 1), (0, 2)})],
       [frozenset({(1, 1), (0, 2), (0, 4)})],
       [frozenset({(1, 1), (0, 2), (0, 4), (4, 3)})],
       [frozenset({(0, 4), (1, 1), (0, 2), (3, 6), (6, 3)})],
       [frozenset({(0, 4), (1, 1), (0, 6), (0, 2), (3, 6), (6, 3)})],
       [frozenset({(2, 4), (0, 4), (1, 1), (4, 6), (6, 6), (0, 2), (5, 3)})],
       [frozenset({(0, 4), (3, 4), (1, 1), (4, 6), (6, 6), (6, 4), (0, 2), (5, 3)})],
       [frozenset({(0, 4), (2, 1), (1, 1), (5, 4), (6, 6), (6, 4), (0, 2), (5, 6), (5, 3)})],
       [frozenset({(1, 2), (0, 4), (1, 1), (4, 6), (0, 6), (0, 2), (2, 2), (6, 6), (3, 2), (6, 3)})],
       [frozenset({(1, 2), (0, 4), (2, 1), (1, 1), (4, 6), (0, 6), (0, 2), (2, 2), (6, 6), (3, 2), (6, 3)})],
       [frozenset({(1, 2), (0, 4), (2, 1), (1, 1), (4, 6), (0, 6), (0, 2), (0, 5), (2, 2), (6, 6), (3, 2), (6, 3)})],
       [frozenset({(1, 2), (0, 4), (4, 0), (1, 1), (6, 4), (0, 6), (0, 2), (5, 0), (5, 6), (6, 6), (3, 2), (6, 3

### Compromise programming ###

In [13]:
from collections import Counter
from pymcdm import weights as obj_w
from compromise_programming import mcdm, ranks2decision

F = problem.evaluate(pareto_optimal_models)
obj_weights = obj_w.entropy_weights(F)
types = [-1, -1]

ranks, prefs = mcdm(F, obj_weights, types)
balance_point, most_common = ranks2decision(ranks)
F[balance_point], most_common, ranks, prefs

(array([6.72030834e-06, 2.00000000e+00]),
 [(1, 4)],
 [array([ 9.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20.]),
  array([12.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 13.,
         14., 15., 16., 17., 18., 19., 20.]),
  array([ 7.,  1.,  2.,  3.,  4.,  5.,  6.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20.]),
  array([12.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 13.,
         14., 15., 16., 17., 18., 19., 20.])],
 [array([0.62701021, 0.9129286 , 0.89881194, 0.86025571, 0.82108143,
         0.77917279, 0.73813835, 0.69846765, 0.65989355, 0.62295516,
         0.5878547 , 0.55403676, 0.52289007, 0.49414418, 0.46802955,
         0.44374214, 0.42198341, 0.40303169, 0.38663581, 0.37298979]),
  array([-0.00357453,  0.28128112,  0.27029538,  0.24361471,  0.22132736,
          0.18955084,  0.15757147,  0.12637073,  0.09444968,  0.06293219,
          0.03174532, -0.00084541, -0.03

In [14]:
# brute_force_all_subsets(X_pre, y_pre, max_support_size=2)